
SELECT COUNT(*)
FROM ORDERS o, CUSTOMER c, SHIPPERS s
WHERE o.CUSTOMER_ID = c.CUSTOMER_ID
AND o.SHIP_VIA = s.SHIPPER_ID
AND s.SHIPPER_ID = 2
AND c.CONTACT_NAME = 'Simons bistro'

--Results = 2